pipeline {
    agent any

    stages {
        stage('Clone Code') {
            steps {
                git 'https://github.com/deviprasannakakaraparthi/todo-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('todo-app') {
                    sh 'docker-compose build'
                }
            }
        }

        stage('Start Services') {
            steps {
                dir('todo-app') {
                    sh 'docker-compose up -d'
                }
            }
        }

        stage('Health Check') {
            steps {
                dir('todo-app') {
                    sh 'sleep 10'
                    sh 'curl --fail http://localhost:3000 || exit 1'
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed.'
        }
    }
}

